before_install:
  - npm i -g https://github.com/isysd-mirror/gpm.git#isysd
  - gpm -n .. -t .. -u https -i iso-test
matrix:
  include:
  - os: linux
    env: BROWSER=chromium-browser
    addons:
      apt:
        packages: chromium-browser
  - os: linux
    env: BROWSER=google-chrome-stable
    addons:
      chrome: "stable"
  - os: linux
    env: BROWSER=firefox
    addons:
      firefox: "latest"
  - os: osx
    env: BROWSER=chromium-browser
    addons:
      homebrew:
        casks: chromium
  - os: osx
    env: BROWSER=google-chrome-stable
    addons:
      chrome: "stable"
  - os: osx
    env: BROWSER=firefox
    addons:
      firefox: "latest"
  - os: osx
    env: BROWSER=safari
    addons:
      homebrew:
        casks: safari
  - os: windows
    env: BROWSER=google-chrome-stable TEST_TIMEOUT=10000
    before_install:
      - choco install googlechrome
      - npm i -g https://github.com/isysd-mirror/gpm.git#isysd
      - gpm -n .. -t .. -u https -i iso-test
# 
# Firefox and Chromium not working on Windows, for some reason :/
#
#  - os: windows
#    env: BROWSER=chromium-browser TEST_TIMEOUT=10000 DEBUG=1
#    before_install: choco install chromium
#  - os: windows
#    env: BROWSER=firefox TEST_TIMEOUT=10000 DEBUG=1
#    before_install: choco install firefox
language: node_js
node_js:
  - "11"
